name: Tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Restore pip cache
              uses: actions/cache@v2
              with:
                  # This path is specific to Ubuntu
                  path: ~/.cache/pip
                  # Look to see if there is a cache hit for the corresponding requirements file
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
                      ${{ runner.os }}-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Test with pytest
              run: |
                pytest -v

            - name: Install package and run
              run: |
                pip install .
                demo -h
