name: Tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Restore pip cache
              uses: actions/cache@v2
              with:
                  # This path is specific to Ubuntu
                  path: ~/.cache/pip
                  # Look to see if there is a cache hit for the corresponding requirements file
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
                      ${{ runner.os }}-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  sed  # TODO: remove - keeps requirements clean
                    -e '/s2let/d'
                    -e '/ssht/d'
                    -i requirements.txt
                  pip install -r requirements.txt

            # TODO: remove fix after packages updated
            - name: Fix conan problems
              run: |
                pip install conan==1.40.2
                conan remote add conan-center https://conan.bintray.com True
                pip install pys2let==2.2.3 pyssht==1.5.0

            - name: Test with pytest
              run: |
                pytest -v

            - name: Install package and run
              run: |
                pip install -e .
                demo -h
